name: Build Debian Live ISO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t debian-live-auto .

      - name: Create output directory
        run: mkdir -p output

      - name: Run live-build in Docker
        run: |
          docker run --rm --privileged \
            -v ${{ github.workspace }}/output:/build/output \
            -v ${{ github.workspace }}/auto:/build/auto \
            debian-live-auto

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-live-iso
          path: output/*.iso
